apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  tls:
    - secretName: web-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - path: /*
          backend:
            serviceName: {{ include "web.fullname" . }}
            servicePort: {{ .Values.service.port }}
