apiVersion: v1
kind: Secret
metadata:
  name: web
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.db.Url }}
  ROLLBAR_TOKEN: {{ .Values.rollbar.Token }}
  SLACK_TOKEN: {{ .Values.slack.Token }}
  DJANGO_AWS_ACCESS_KEY_ID: {{ .Values.aws.AccessKey }}
  DJANGO_AWS_SECRET_ACCESS_KEY: {{.Values.aws.SecretKey }}
  MAILGUN_API_KEY: {{ .Values.mailgun.Key }}
  DJANGO_SECRET_KEY: {{.Values.django.SecretKey }}
  SOCIAL_AUTH_GITHUB_SECRET: {{ .Values.socialAuth.github.secret }}
  SOCIAL_AUTH_GITHUB_KEY: {{ .Values.socialAuth.github.key }}
  CONTENT_SECURITY_POLICY: {{ .Values.django.contentSecurityPolicy }}
  DJANGO_ADMIN_URL: {{ .Values.django.adminUrl }}
  DJANGO_AWS_S3_REGION_NAME: {{ .Values.aws.region }}
  DJANGO_AWS_STORAGE_BUCKET_NAME: {{ .Values.aws.bucketName }}
  GITHUB_REDIRECT_URI: {{ .Values.socialAuth.github.redirectUri }}
  SLACK_INVITE_URL: {{ .Values.slack.inviteUrl }}
  MAILGUN_DOMAIN: {{ .Values.mailgun.domain }}
  DJANGO_SERVER_EMAIL: {{ .Values.mailgun.email }}
  DJANGO_ALLOWED_HOSTS: {{ default .Values.django.allowedHosts '*' }}
  DJANGO_SETTINGS_MODULE: {{ .Values.django.settings }}
  REDIS_URL: "doesnt-matter"


