apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    type: horizontal
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        date: '{{ now.Unix }}'
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        env:
        - name: HELM_CHART
          value: '{{ .Chart.Name }}'
        - name: HELM_RELEASE
          value: '{{ .Release.Name }}'
        - name: USE_DOCKER
          value: 'yes'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: name
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: port
        - name: X_SECUREAPI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: boatswain-web
              key: authKey
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
