# Generated by Django 2.0.13 on 2019-12-14 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecTest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'sectest',
            },
        ),
        migrations.CreateModel(
            name='SecTestSuite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'sectestsuite',
            },
        ),
        migrations.AddField(
            model_name='sectest',
            name='suite',
            field=models.ForeignKey(db_column='suite', on_delete=django.db.models.deletion.DO_NOTHING, to='sectests.SecTestSuite'),
        ),
    ]
