# Generated by Django 2.0.13 on 2019-05-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sectests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', model_utils.fields.StatusField(choices=[('passed', 'passed'), ('failed', 'failed'), ('error', 'error')], default='passed', max_length=100, no_check_for_status=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecTestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('security_index', models.FloatField(null=True)),
                ('tests', models.ManyToManyField(to='sectests.SecTest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.RemoveField(
            model_name='secerror',
            name='id',
        ),
        migrations.AlterField(
            model_name='secerror',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sectest',
            name='error_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectests.SecError'),
        ),
    ]
