# Generated by Django 2.0.13 on 2020-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectests', '0003_auto_20200222_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectestsuite',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='sectestsuite',
            name='origin',
            field=models.CharField(default='local_or_other', max_length=50),
        ),
    ]
