#!/bin/sh

set -o errexit
set -o nounset

# Prepare log files and start outputting logs to stdout
touch /var/log/gunicorn.log
touch /var/log/gunicorn-access.log
tail -n 0 -f /var/log/gunicorn*.log &

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --log-level=info --log-file=/var/log/gunicorn.log --access-logfile=/var/log/gunicorn-access.log
