image:
  repository: secureapi/web
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: dockerhubpull

replicas: 1

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  externalPort: 80
  internalPort: 8000
