# Generated by Django 2.0.13 on 2019-05-02 12:34

from django.db import migrations, models
import secureapi_web.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clitoken',
            name='token',
            field=models.CharField(default=secureapi_web.users.utils.cli_token_gen, max_length=36),
        ),
    ]
